### ISSUE TITLE
Ambassador needs to support an authentication service

### ISSUE THREAD

**Issue by kflynn** [datawire/ambassador#9]
As it stands, anyone in the world can do anything. That's obviously unacceptable.

The most straightforward way to handle this is to take request headers and hand them off to an auth service (which, naturally, will be vectored through Ambassador).

DoD:
- [x] There exists an Envoy auth filter can call a REST service to get a go/no-go decision (GH #59)
- [x] Datawire CI publishes a Docker image with an Envoy that includes the auth filter
- [x] There exists a reference auth service that the auth filter can talk to
- [x] Datawire CI publishes a Docker image with the auth service 
- [x] Ambassador can be configured via REST call to use the auth filter, talking to a named auth service
- [x] Ambassador knows how to configure Envoy according to the configuration call above
- [x] Ambassador configuration is documented (#67)
- [x] REST API is documented (#67)

**Comment by kflynn** [comment]
Current status:

- extauth filter works
- extauth service works
- Ambassador interface needs a release

**Comment by kflynn** [comment]
Reopening until docs are fully pushed.

**Comment by kflynn** [comment]
Done.
